export const products = [
    {
        id: 1,
        name: "Camera",
        category: "Electronics",
        price: 40,
        image: "/images/products/camera.jpg",
        inCart: false,
        desc: "A digital camera.",
    },
    {
        id: 2,
        name: "Headphones",
        category: "Electronics",
        price: 20,
        image: "/images/products/headphones.png",
        inCart: false,
        desc: "A pair of headphones.",
    },
    {
        id: 3,
        name: "Canned Tomatoes",
        category: "Food",
        price: 5,
        image: "/images/products/canned tomato.jpg",
        inCart: false,
        desc: "A delicious can of tomatoes!",
    },
    {
        id: 4,
        name: "Chess",
        category: "Board game",
        price: 8,
        image: "/images/products/chess.jpg",
        inCart: false,
        desc: "An intriguing board game, dating back to the 6th century.",
    },
    {
        id: 5,
        name: "Dumbbell",
        category: "Fitness",
        price: 9,
        image: "/images/products/dumbbell.jpg",
        inCart: false,
        desc: "A 10-pound dumbbell for your home gym.",
    },
    {
        id: 6,
        name: "Indoor Plant",
        category: "Decor",
        price: 15,
        image: "/images/products/indoor plant.jpg",
        inCart: false,
        desc: "A beautiful, green plant meant to liven up your home.",
    },
    {
        id: 7,
        name: "Jenga",
        category: "Board game",
        price: 12,
        image: "/images/products/jenga.jpg",
        inCart: false,
        desc: "A classic block-stacking game for all ages.",
    },
    {
        id: 8,
        name: "Laptop",
        category: "Electronics",
        price: 800,
        image: "/images/products/laptop.jpg",
        inCart: false,
        desc: "A powerful laptop for work or play.",
    },
    {
        id: 9,
        name: "Lego",
        category: "Toys",
        price: 25,
        image: "/images/products/lego.png",
        inCart: false,
        desc: "A set of Lego blocks for building and creating.",
    },
    {
        id: 10,
        name: "Mini Figure",
        category: "Toys",
        price: 3,
        image: "/images/products/mini figure.jpg",
        inCart: false,
        desc: "A small Lego figure to add to your collection.",
    },
    {
        id: 11,
        name: "Notebook",
        category: "Office Supplies",
        price: 6,
        image: "/images/products/notebook.jpg",
        inCart: false,
        desc: "A lined notebook for jotting down notes and ideas.",
    },
    {
        id: 12,
        name: "Smartphone",
        category: "Electronics",
        price: 600,
        image: "/images/products/smartphone.jpg",
        inCart: false,
        desc: "A high-end smartphone with all the latest features.",
    },
    {
        id: 13,
        name: "Snakes and Ladders",
        category: "Board game",
        price: 10,
        image: "/images/products/snakes and ladders.jpg",
        inCart: false,
        desc: "A classic board game for all ages.",
    },
    {
        id: 14,
        name: "Sunglasses",
        category: "Accessories",
        price: 15,
        image: "/images/products/sunglasses.jpg",
        inCart: false,
        desc: "A stylish pair of sunglasses to protect your eyes from the sun.",
    },
    {
        id: 15,
        name: "Watch",
        category: "Accessories",
        price: 50,
        image: "/images/products/watch.jpg",
        inCart: false,
        desc: "A sleek and stylish watch to keep you on time.",
    },
];
